### ISSUE TITLE
CountryRegionIso2 not supported?

### ISSUE THREAD

**Issue by mms-** [dkackman/PortableBingGeocoder#3]
Bing query parameter incl=ciso2 returns an additional field CountryRegionIso2 which is not readable by this lib?

https://msdn.microsoft.com/en-us/library/ff701710.aspx

**Comment by dkackman** [comment]
Indeed it doesn't. I'll add.

**Comment by dkackman** [comment]
Check out the latest code and the GetAddressCISO2 unit test in this file:
https://github.com/dkackman/PortableBingGeocoder/blob/master/GeoCoderTests/AddressTests.cs 

If it all looks hunky dory I'll push a nugget update.

**Comment by mms-** [comment]
Looks good, thanks!

**Comment by dkackman** [comment]
Nuget package 2.0 has this support 
https://github.com/dkackman/PortableBingGeocoder/releases/tag/2.0.0
